server:
  port: 8087

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5438}/${DB_NAME:notificationdb}
    username: ${SPRING_DATASOURCE_USERNAME:notification}
    password: ${SPRING_DATASOURCE_PASSWORD:notification}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  cloud:
    inetutils:
      ignored-interfaces:
        - ecs-eth0
      preferred-networks:
        - 10.0
    aws:
      region:
        static: ${AWS_REGION:eu-central-1}
      sqs:
        enabled: false

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  whatsapp-from: ${TWILIO_WHATSAPP_FROM:whatsapp:+14155238886}

jwt:
  secret: ${JWT_SECRET}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:discovery-server}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
