management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5434/customerdb   # lokal; Docker: postgres-customer:5432
    username: ${SPRING_DATASOURCE_USERNAME:customer}
    password: ${SPRING_DATASOURCE_PASSWORD:customer}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

eureka: # implement later
  client:
    service-url:
      defaultZone: