server:
  port: 8083

spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5436/deliverydb  # lokal; Docker: postgres-delivery:5432
    username: ${SPRING_DATASOURCE_USERNAME:delivery}
    password: ${SPRING_DATASOURCE_PASSWORD:delivery}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
